name: caller_wf
on: 
  workflow_dispatch:
    inputs:
      environment:
        default: 'abc'
        required: true
        type: 'string'
jobs:
  jobx:
      environment: abc
      runs-on: self-hosted
      uses: anupam-test-org/called/.github/workflows/one.yaml@main
